apiVersion: v1
kind: Service
metadata:
  name: helloworld
  namespace: default
  labels:
    app: helloworld
spec:
  selector:
    app: helloworld
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 8080
