apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: helloworld
      context: ../argo-test
      jib: {}
  tagPolicy:
    envTemplate:
      template: '{{.IMAGE_NAME}}:latest'
deploy:
  kustomize: {}
